### PR TITLE
V13 Support

### PR DESCRIPTION
**Pull request by Simpleboy353**

### CODE REVIEW

**Comment by HACKERPROTM** [comment]
You need to fix antilink and welcome it just spams the message after two trys

**Comment by HACKERPROTM** [comment]
I recommend deleting the data2 since thats were the spam come from and add a emmiter.setMaxlisteners on your index or main

**Comment by Simpleboy353** [comment]
> You need to fix antilink and welcome it just spams the message after two trys

I added some changes to these files, you can try them now, I haven't tested the changes so please report the errors you face (if any)

**Comment by Simpleboy353** [comment]
> I recommend deleting the data2 since thats were the spam come from and add a emmiter.setMaxlisteners on your index or main

Deleting data2 isn't an option as it is required to check whether a custom message has been stored or not

> if u want also i can add some commands i have. If u want some commands chexk them here https://www.xopbot.tk/ i would be happy to help you

Any help in any form is appreciated. Feel free to open pull requests, if you have any feature that can be added to this repository

**Pull request merged**
